# Spanish translations for PACKAGE package.
# Copyright (C) 2015 THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# root <amp_21004@yahoo.es>, 2015.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-03-18 13:00+0100\n"
"PO-Revision-Date: 2015-09-29 17:13+0200\n"
"Last-Translator: root <amp_21004@yahoo.es>\n"
"Language-Team: Spanish\n"
"Language: es\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: ../data/glade/autoconf.glade:320 ../data/glade/autoconf.glade:352
msgid " "
msgstr " "

#: ../data/glade/main.glade:362 ../data/glade/requirements.glade:694
#: ../data/glade/window.glade:25
msgid "127.0.0.1"
msgstr ""

#: ../data/glade/main.glade:366 ../data/glade/requirements.glade:698
#: ../data/glade/window.glade:29
msgid "192.168.1.99"
msgstr ""

#: ../data/glade/gecoscon.glade:335
msgid "<b>Connection with GECOS</b>"
msgstr "<b>Conexión con GECOS</b>"

#: ../data/glade/gecoscon.glade:460
msgid "<b>OU selection</b>"
msgstr "<b>Selección de OU</b>"

#: ../data/glade/gecoscon.glade:213
msgid "<b>Workstation name</b>"
msgstr "<b>Nombre de la estación</b>"

#: ../data/glade/adsetupdata.glade:126 ../data/glade/localuserpopup.glade:204
msgid "Accept"
msgstr "Aceptar"

#: ../data/glade/ntp.glade:244 ../data/glade/progress.glade:180
#: ../data/glade/users.glade:427
msgid "Accept "
msgstr "Aceptar "

#: ../data/glade/localuserpopup.glade:6
msgid "Add local user"
msgstr "Añadir usuario local"

#: ../data/glade/users.glade:167
msgid "Authentication Method Setup"
msgstr "Configurar el Método de Autenticación"

#: ../data/glade/autoconf.glade:84 ../data/glade/main.glade:94
#: ../data/glade/network.glade:99 ../data/glade/ntp.glade:78
#: ../data/glade/requirements.glade:94 ../data/glade/users.glade:87
#: ../data/glade/users.glade:215
msgid "Authentication type"
msgstr "Tipo de autenticación"

#: ../data/glade/autoconf.glade:167
msgid "Auto setup"
msgstr "Auto setup"

#: ../data/glade/users.glade:373
msgid "Base group:"
msgstr "DN Base para grupos:"

#: ../data/glade/users.glade:360
msgid "Base:"
msgstr "DN Base:"

#: ../data/glade/requirements.glade:241
msgid "Basic setup values got from GECOS server"
msgstr "Valores de configuración obtenidos del servidor"

#: ../data/glade/users.glade:386
msgid "Bind DN:"
msgstr "DN para enlace:"

#: ../data/glade/users.glade:399
msgid "Bind password:"
msgstr "Contraseña para enlace:"

#: ../data/glade/adsetupdata.glade:144 ../data/glade/localuserpopup.glade:185
msgid "Cancel"
msgstr "Cancelar"

#: ../data/glade/ntp.glade:206
msgid "Check"
msgstr "Comprobar"

#: ../data/glade/progress.glade:21
msgid "Check GECOS credentials "
msgstr "Comprobar credenciales de GECOS "

#: ../data/glade/progress.glade:34
msgid "Check workstation data "
msgstr "Comprobar datos del puesto de trabajo"

#: ../data/glade/progress.glade:94
msgid "Clean up setup data"
msgstr "Limpiar los datos de configuración"

#: ../data/glade/autoconf.glade:530 ../data/glade/gecoscon.glade:707
#: ../data/glade/main.glade:325 ../data/glade/network.glade:450
#: ../data/glade/ntp.glade:445 ../data/glade/requirements.glade:657
#: ../data/glade/users.glade:621 ../data/glade/window.glade:322
msgid "Close"
msgstr "Cerrar"

#: ../data/glade/requirements.glade:449
msgid "Configure"
msgstr "Configurar"

#: ../data/glade/network.glade:266
msgid "Configure network connection"
msgstr "Configurar la conexión de red"

#: ../data/glade/localuserpopup.glade:83
msgid "Confirm:"
msgstr "Confirmar:"

#: ../data/glade/gecoscon.glade:486
msgid "Connect to CC GECOS"
msgstr "Conectar al CC GECOS"

#: ../data/glade/localusers.glade:156
msgid "Delete"
msgstr "Borrar"

#: ../data/glade/adsetupdata.glade:70
msgid "Domain:"
msgstr "Dominio:"

#: ../data/glade/autoconf.glade:17 ../data/glade/gecoscon.glade:13
#: ../data/glade/main.glade:27 ../data/glade/network.glade:35
#: ../data/glade/ntp.glade:16 ../data/glade/requirements.glade:27
#: ../data/glade/users.glade:23 ../data/glade/window.glade:35
msgid "GECOS Config Assistant"
msgstr "Asistente de configuración GECOS"

#: ../data/glade/gecoscon.glade:133
msgid "GECOS Control Center URL"
msgstr "URL del Centro de Control GECOS"

#: ../data/glade/gecoscon.glade:117
msgid "GECOS Control Center connection setup"
msgstr "Configuración de la conexión con el Centro de Control GECOS"

#: ../data/glade/autoconf.glade:207
msgid "GECOS URL"
msgstr "URL de GECOS"

#: ../data/glade/progress.glade:49
msgid "Get chef certificate "
msgstr "Obtener certificado de chef"

#: ../data/glade/autoconf.glade:299 ../data/glade/requirements.glade:431
msgid "Get data"
msgstr "Obtener datos"

#: ../data/glade/autoconf.glade:334 ../data/glade/localusers.glade:173
#: ../data/glade/network.glade:247 ../data/glade/systemstatus.glade:63
#: ../data/glade/users.glade:442
msgid "Go Back"
msgstr "Volver"

#: ../data/glade/gecoscon.glade:527 ../data/glade/ntp.glade:260
msgid "Go back"
msgstr "Volver"

#: ../data/glade/localusers.glade:59
msgid ""
"It isn't necessary to create here the users that are authenticated by "
"external services (LDAP, AD, ...)"
msgstr ""
"No es necesario crear aquí los usuarios que se autentican por servicios "
"externos (LDAP, AD, ...)"

#: ../data/glade/gecoscon.glade:181
msgid ""
"It must be unique, it can use white spaces or symbols. It would be the "
"description on the reports."
msgstr ""
"Debe ser único. Pueden usarse espacios o símbolos. Será usado como "
"descripción en los informes."

#: ../data/glade/requirements.glade:467
msgid "Link"
msgstr "Vincular"

#: ../data/glade/progress.glade:64
msgid "Link to chef "
msgstr "Vincular a Chef "

#: ../data/glade/autoconf.glade:48 ../data/glade/main.glade:57
#: ../data/glade/network.glade:66 ../data/glade/ntp.glade:47
#: ../data/glade/requirements.glade:57 ../data/glade/users.glade:54
msgid "Link/Unlink"
msgstr "Vincular/Desvincular"

#: ../data/glade/autoconf.glade:457 ../data/glade/gecoscon.glade:634
#: ../data/glade/main.glade:252 ../data/glade/network.glade:377
#: ../data/glade/ntp.glade:373 ../data/glade/requirements.glade:584
#: ../data/glade/users.glade:548 ../data/glade/window.glade:233
msgid "Local Users"
msgstr "Usuarios locales"

#: ../data/glade/gecoscon.glade:502
msgid "Local disconnection?"
msgstr "¿Desconexión local?"

#: ../data/glade/localuserpopup.glade:45
msgid "Login:"
msgstr "Login:"

#: ../data/glade/localusers.glade:24
msgid "Manage local users"
msgstr "Gestionar usuarios locales"

#: ../data/glade/requirements.glade:485
msgid "Modify"
msgstr "Modificar"

#: ../data/glade/ntp.glade:156
msgid "NTP Server configuration"
msgstr "Configuración del servidor NTP"

#: ../data/glade/ntp.glade:195
msgid "NTP Server:"
msgstr "Servidor NTP:"

#: ../data/glade/localuserpopup.glade:26
msgid "Name:"
msgstr "Nombre:"

#: ../data/glade/network.glade:178
msgid "Network Setup"
msgstr "Configuración de Red"

#: ../data/glade/requirements.glade:189
msgid "Network connection"
msgstr "Conexión de red"

#: ../data/glade/autoconf.glade:183 ../data/glade/network.glade:194
msgid ""
"Network connection parameters with GECOS Control Center are mandatory for "
"auto setup"
msgstr ""
"Los datos de conexión con el Centro de Control GECOS son necesarios para la "
"autoconfiguración"

#: ../data/glade/localusers.glade:122
msgid "New"
msgstr "Nuevo"

#: ../data/glade/gecoscon.glade:388
msgid "OU"
msgstr ""

#: ../data/glade/progress.glade:106 ../data/glade/progress.glade:117
#: ../data/glade/progress.glade:130 ../data/glade/progress.glade:143
#: ../data/glade/progress.glade:156 ../data/glade/progress.glade:169
msgid "PENDING "
msgstr "PENDIENTE "

#: ../data/glade/autoconf.glade:235 ../data/glade/gecoscon.glade:271
msgid "Password"
msgstr "Contraseña"

#: ../data/glade/adsetupdata.glade:115 ../data/glade/localuserpopup.glade:64
msgid "Password:"
msgstr "Contraseña:"

#: ../data/glade/localusers.glade:82
msgid "Please check default OEM users and change their passwords when needed:"
msgstr ""
"Por favor revise los usuarios OEM y cambie sus contraseñas si es necesario:"

#: ../data/glade/ntp.glade:172
msgid ""
"Precise time is needed to keep some services synchronized.\n"
"Please set your NTP server address:"
msgstr ""
"Se necesita una hora precisa parra mantener algunos servicios "
"sincronizados.\n"
"Por favor configure su servidor NTP:"

#: ../data/glade/progress.glade:79
msgid "Register in GECOS CC "
msgstr "Registrar en CC GECOS"

#: ../data/glade/gecoscon.glade:411
msgid "Search"
msgstr "Buscar"

#: ../data/glade/window.glade:307
msgid "See Log"
msgstr "Ver log"

#: ../data/glade/autoconf.glade:500 ../data/glade/gecoscon.glade:677
#: ../data/glade/main.glade:295 ../data/glade/network.glade:420
#: ../data/glade/ntp.glade:415 ../data/glade/requirements.glade:627
#: ../data/glade/users.glade:591 ../data/glade/window.glade:277
msgid "Software Manager"
msgstr "Gestor de Software"

#: ../data/glade/autoconf.glade:414 ../data/glade/gecoscon.glade:591
#: ../data/glade/main.glade:209 ../data/glade/network.glade:334
#: ../data/glade/ntp.glade:331 ../data/glade/requirements.glade:541
#: ../data/glade/users.glade:505 ../data/glade/window.glade:189
msgid "System Status"
msgstr "Estado del Sistema"

#: ../data/glade/systemstatus.glade:11
msgid "System status"
msgstr "Estado del Sistema"

#: ../data/glade/users.glade:196
msgid ""
"The users of this workstation may authenticate by using an external system "
"like LDAP or Microsoft Active Directory. Also, they can be authenticated by "
"using local users of this O.S."
msgstr ""
"Los usuarios de esta estación pueden autenticarse mediante un sistema "
"externo como LDAP o Microsoft Active Directory. También pueden autenticarse "
"usando usuarios locales de este Sistema Operativo"

#: ../data/glade/requirements.glade:211
msgid "This workstation has got a network connection configured"
msgstr "Este puesto dispone de conexión a red (datos de conexión)"

#: ../data/glade/requirements.glade:309
msgid "This workstation is NOT linked to a Control Center"
msgstr "Este puesto NO está vinculado a un Centro de Control"

#: ../data/glade/requirements.glade:275
msgid "This workstation is NOT synchronized with a time server (NTP)"
msgstr "Este puesto NO está sincronizado con un servidor de hora (NTP)"

#: ../data/glade/adsetupdata.glade:167
msgid ""
"To disconnect from Active Directory you need \n"
"to enter the Administrator user and password:"
msgstr ""
"Para desconectar de Active Directory necesitará \n"
"introducir el usuario Administrador y su contraseña:"

#: ../data/glade/users.glade:351
msgid "URI:"
msgstr ""

#: ../data/glade/localusers.glade:139
msgid "Update"
msgstr "Actualizar"

#: ../data/glade/autoconf.glade:221 ../data/glade/gecoscon.glade:259
msgid "User"
msgstr "Usuario"

#: ../data/glade/adsetupdata.glade:100
msgid "User:"
msgstr "Usuario:"

#: ../data/glade/requirements.glade:343
msgid "Users authenticate themselves using the INTERNAL method"
msgstr "Los usuarios se autentican usando el método INTERNO"

#: ../data/glade/adsetupdata.glade:85
msgid "Workgroup:"
msgstr "Grupo de trabajo:"

#: ../data/glade/localusers.glade:43
msgid "You can create, update or delete local users in this workstation."
msgstr ""
"Puede crear, actualizar o borrar usuarios locales en esta estación de "
"trabajo."

#: ../data/glade/main.glade:365 ../data/glade/requirements.glade:697
#: ../data/glade/window.glade:28
msgid "eth0"
msgstr ""

#: ../data/glade/gecoscon.glade:149
msgid "http://"
msgstr ""

#: ../data/glade/main.glade:361 ../data/glade/requirements.glade:693
#: ../data/glade/window.glade:24
msgid "lo"
msgstr ""

#: ../gecosws_config_assistant/view/LogTerminalDialog.py:135
msgid "Log terminal"
msgstr "Terminal de Log"

#: ../gecosws_config_assistant/view/GecosCCSetupProgressView.py:121
#: ../gecosws_config_assistant/view/GecosCCSetupProgressView.py:128
#: ../gecosws_config_assistant/view/GecosCCSetupProgressView.py:135
#: ../gecosws_config_assistant/view/GecosCCSetupProgressView.py:148
#: ../gecosws_config_assistant/view/GecosCCSetupProgressView.py:161
#: ../gecosws_config_assistant/view/GecosCCSetupProgressView.py:168
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:415
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:421
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:428
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:440
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:477
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:490
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:615
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:633
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:647
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:668
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:759
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:775
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:805
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:829
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:853
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:874
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:894
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:947
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:960
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:987
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:998
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:1006
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:1015
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:1027
msgid "ERROR"
msgstr ""

#: ../gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:175
msgid "Disconnect from CC GECOS"
msgstr "Desconectar del CC GECOS"

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:105
#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:108
msgid "Assistant version: "
msgstr "Versión del asistente: "

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:109
msgid "UNKNOWN VERSION"
msgstr "VERSIÓN DESCONOCIDA"

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:114
msgid "Workstation name: "
msgstr "Nombre de la estación: "

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:120
msgid "Time server: "
msgstr "Servidor NTP: "

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:123
msgid "Network interfaces: "
msgstr "Interfaces de red: "

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:131
msgid "GECOS Control Center connection data: "
msgstr "Datos de conexión con el Centro de Control GECOS: "

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:135
msgid "Server URL:"
msgstr "URL del servidor:"

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:139
msgid "Local users: "
msgstr "Usuarios locales: "

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:146
msgid "User authentication method: "
msgstr "Método de Autenticación de usuarios: "

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:149
msgid "Method:"
msgstr "Método: "

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:158
msgid "Server URI:"
msgstr "URI del servidor:"

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:160
#: ../gecosws_config_assistant/view/UserAuthDialog.py:248
msgid "Users base DN:"
msgstr "DN base de usuarios:"

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:162
msgid "Groups base DN:"
msgstr "DN base de grupos:"

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:167
msgid "No status data!"
msgstr "¡No hay información de estado!"

#: ../gecosws_config_assistant/view/ADSetupDataElemView.py:125
msgid ""
"Can't connect to Active Directory.\n"
"Please double-check all the fields"
msgstr ""
"No se ha podido conectar con el Active Directory.\n"
"Por favor revise todos los campos"

#: ../gecosws_config_assistant/view/UserAuthDialog.py:69
#: ../gecosws_config_assistant/view/UserAuthDialog.py:165
#: ../gecosws_config_assistant/view/UserAuthDialog.py:212
#: ../gecosws_config_assistant/controller/MainMenuController.py:235
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:248
#: ../gecosws_config_assistant/dto/LocalUsersAuthMethod.py:47
#: ../gecosws_config_assistant/tests/dto/LocalUsersAuthMethodTest.py:39
msgid "Internal"
msgstr "Interno"

#: ../gecosws_config_assistant/view/UserAuthDialog.py:69
#: ../gecosws_config_assistant/view/UserAuthDialog.py:167
#: ../gecosws_config_assistant/view/UserAuthDialog.py:214
#: ../gecosws_config_assistant/controller/MainMenuController.py:231
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:250
#: ../gecosws_config_assistant/dto/LDAPAuthMethod.py:48
#: ../gecosws_config_assistant/tests/dto/LDAPAuthMethodTest.py:40
msgid "LDAP"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:69
#: ../gecosws_config_assistant/view/UserAuthDialog.py:169
#: ../gecosws_config_assistant/view/UserAuthDialog.py:216
#: ../gecosws_config_assistant/controller/MainMenuController.py:233
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:252
#: ../gecosws_config_assistant/dto/ADAuthMethod.py:45
#: ../gecosws_config_assistant/tests/dto/ADAuthMethodTest.py:40
msgid "Active Directory"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:244
msgid "Please fill the data to setup the LDAP authentication method."
msgstr ""
"Por favor rellene todos los datos para configurar el méotod de autenticación "
"por LDAP."

#: ../gecosws_config_assistant/view/UserAuthDialog.py:247
msgid "LDAP server URI:"
msgstr "URI del servidor LDAP:"

#: ../gecosws_config_assistant/view/UserAuthDialog.py:249
msgid "Groups base DN (optional):"
msgstr "DN base de grupos (opcional):"

#: ../gecosws_config_assistant/view/UserAuthDialog.py:250
msgid "Bind user DN (optional):"
msgstr "DN del usuario para enlazar (opcional):"

#: ../gecosws_config_assistant/view/UserAuthDialog.py:251
msgid "Bind user password (optional):"
msgstr "Contraseña para enlace (opcional):"

#: ../gecosws_config_assistant/view/UserAuthDialog.py:286
msgid ""
"Please fill the data to setup the Active Directory authentication method."
msgstr ""
"Por favor rellene los datos para configurar el método de autenticación mediante Active Directory."


#: ../gecosws_config_assistant/view/UserAuthDialog.py:292
msgid "(Active Directory) User:"
msgstr "(Active Directory) Usuario:"

#: ../gecosws_config_assistant/view/UserAuthDialog.py:293
msgid "(Active Directory) Password:"
msgstr "(Active Directory) Contraseña:"

#: ../gecosws_config_assistant/view/UserAuthDialog.py:327
msgid ""
"Specific configuration data was loaded from GECOS server\n"
"(sssd.conf, krb5.conf, smb.conf and pam.conf)"
msgstr ""
"Se ha descargado desde el Centro de Control GECOS datos de configuración\n"
"específicos (sssd.conf, krb5.conf, smb.conf y pam.conf)"

#: ../gecosws_config_assistant/view/UserAuthDialog.py:362
msgid ""
"There is no necessary data to setup the local users authentication method."
msgstr ""
"No se necesita configuración para usar el método de autenticación por "
"usuarios locales."

#: ../gecosws_config_assistant/view/UserAuthDialog.py:513
msgid "An error happened while saving the users authentication method!"
msgstr "¡Ocurrió un error al guardar el método de autenticación de usuarios!"

#: ../gecosws_config_assistant/view/UserAuthDialog.py:515
#: ../gecosws_config_assistant/controller/NTPServerController.py:96
#: ../gecosws_config_assistant/controller/NTPServerController.py:102
msgid "See log for more details."
msgstr "Vea el log para más detalles."

#: ../gecosws_config_assistant/view/LocalUserElemDialog.py:95
msgid "Modifiy local user"
msgstr "Modificar usuario local"

#: ../gecosws_config_assistant/view/LocalUserElemDialog.py:137
msgid "The password confirmation field is empty!"
msgstr "El campo Confirmación de la clave está vacío!"

#: ../gecosws_config_assistant/view/LocalUserElemDialog.py:138
#: ../gecosws_config_assistant/controller/AutoSetupController.py:115
#: ../gecosws_config_assistant/controller/AutoSetupController.py:206
#: ../gecosws_config_assistant/controller/AutoSetupController.py:218
#: ../gecosws_config_assistant/controller/LocalUserController.py:85
#: ../gecosws_config_assistant/controller/LocalUserController.py:102
#: ../gecosws_config_assistant/controller/LocalUserController.py:111
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:419
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:438
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:474
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:507
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:517
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:527
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:128
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:149
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:160
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:261
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:279
msgid "Please fill all the mandatory fields."
msgstr "Por favor rellene todos los campos obligatorios."

#: ../gecosws_config_assistant/view/LocalUserElemDialog.py:147
msgid "The password confirmation is different from password"
msgstr "El campo confirmación de la clave es diferente del campo clave"

#: ../gecosws_config_assistant/view/NTPServerElemView.py:129
msgid ""
"Can't connect with NTP server.\n"
"Please double-check the NTP server address"
msgstr ""
"No se puede conectar con el servidor NTP.\n"
"Por favor revise la dirección del servidor NTP"

#: ../gecosws_config_assistant/view/NTPServerElemView.py:133
msgid "NTP server connection successful"
msgstr "Éxito al configurar el servidor NTP"

#: ../gecosws_config_assistant/view/MainWindow.py:209
msgid "Link with GECOS server"
msgstr "Enlazar al servidor GECOS"

#: ../gecosws_config_assistant/view/MainWindow.py:211
msgid ""
"You must link your workstation with a GECOS server to be \n"
"able to manage this workstation in a centralized way"
msgstr ""
"Debe enlazar su estación de trabajo con el servidor GECOS para \n"
"poder gestionarla de una forma centralizada"

#: ../gecosws_config_assistant/view/MainWindow.py:222
msgid "Setup user authentication method"
msgstr "Configurar el Método de Autenticación"

#: ../gecosws_config_assistant/view/MainWindow.py:224
msgid ""
"You must setup the user authentication method to either: internal users, "
"LDAP or Active Directory"
msgstr ""
"Debe configurar su método de autenticación de usuarios como: usuarios "
"internos, LDAP o Active Directory"

#: ../gecosws_config_assistant/view/MainWindow.py:410
msgid "Unlink"
msgstr "Desvincular"

#: ../gecosws_config_assistant/view/SplashScreen.py:55
msgid "Loading ..."
msgstr "Cargando ..."

#: ../gecosws_config_assistant/util/GtkAptProgress.py:251
#, python-format
msgid "Downloading file %(current)li of %(total)li with %(speed)s/s"
msgstr "Descargando fichero %(current)li de %(total)li a %(speed)s/s"

#: ../gecosws_config_assistant/util/GtkAptProgress.py:257
#, python-format
msgid "Downloading file %(current)li of %(total)li"
msgstr "Descargando fichero %(current)li de %(total)li"

#: ../gecosws_config_assistant/util/GtkAptProgress.py:280
msgid "Details"
msgstr "Detalles"

#: ../gecosws_config_assistant/util/GtkAptProgress.py:354
msgid "Starting..."
msgstr "Iniciando..."

#: ../gecosws_config_assistant/util/GtkAptProgress.py:360
msgid "Complete"
msgstr "Completado"

#: ../gecosws_config_assistant/controller/NTPServerController.py:95
#: ../gecosws_config_assistant/controller/NTPServerController.py:101
msgid "Error saving NTP server data."
msgstr "Error guardando los datos del servidor de NTP"

#: ../gecosws_config_assistant/controller/MainMenuController.py:203
msgid "This workstation has NO network connection"
msgstr "El sistema no dispone de conexión a red"

#: ../gecosws_config_assistant/controller/MainMenuController.py:207
msgid "This worstation has loaded setup data values from Control Center"
msgstr ""
"El sistema ha cargado los valores de configuración desde el servidor de GECOS"

#: ../gecosws_config_assistant/controller/MainMenuController.py:210
msgid "This workstation can load setup data values from Control Center"
msgstr ""
"El sistema cargará los datos de configuración desde el servidor de GECOS"

#: ../gecosws_config_assistant/controller/MainMenuController.py:214
msgid "This workstation is synchronized with a time server (NTP)"
msgstr "Este puesto NO está sincronizado con un servidor de hora (NTP)"

#: ../gecosws_config_assistant/controller/MainMenuController.py:221
msgid "This workstation is linked to a Control Center"
msgstr "Este puesto está vinculado a un Centro de Control"

#: ../gecosws_config_assistant/controller/MainMenuController.py:226
#, python-format
msgid "Users authenticate themselves with %s"
msgstr "Los usuarios se autentican usando %s"

#: ../gecosws_config_assistant/controller/MainMenuController.py:318
#: ../gecosws_config_assistant/controller/MainMenuController.py:356
msgid "Upgrading ..."
msgstr "Actualizando ..."

#: ../gecosws_config_assistant/controller/MainMenuController.py:368
msgid "Unable to connect to software repository"
msgstr "¡No se puede conectar al repositorio de software!"

#: ../gecosws_config_assistant/controller/MainMenuController.py:374
msgid "An error occurred during the upgrade"
msgstr "Ha ocurrido un problema durante la actualización"

#: ../gecosws_config_assistant/controller/MainMenuController.py:384
msgid "Installing gems ..."
msgstr "Instalando gemas ..."

#: ../gecosws_config_assistant/controller/MainMenuController.py:395
msgid "An error ocurred while installing gems"
msgstr "Ha ocurrido un problema durante la actualización"

#: ../gecosws_config_assistant/controller/MainMenuController.py:405
msgid "GECOS Config Assistant has been udpated. Restarting ..."
msgstr ""
"El Asistente de Configuración GECOS se ha actualizado. Reiniciando ... "

#: ../gecosws_config_assistant/controller/AutoSetupController.py:113
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:126
msgid "The URL field is empty!"
msgstr "¡El campo URL está vacío!"

#: ../gecosws_config_assistant/controller/AutoSetupController.py:123
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:136
msgid "Malformed URL in URL field!"
msgstr "¡URL mal escrita en el campo URL!"

#: ../gecosws_config_assistant/controller/AutoSetupController.py:124
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:138
msgid "Please double-check it."
msgstr "Por favor revise el dato."

#: ../gecosws_config_assistant/controller/AutoSetupController.py:152
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:189
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:579
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:729
msgid "The certificate of this server is expired!"
msgstr "¡El certificado de este servidor ha expirado!"

#: ../gecosws_config_assistant/controller/AutoSetupController.py:156
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:193
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:583
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:733
msgid "The certificate of this server is not trusted!"
msgstr "¡No se confía en el certificado de este servidor!"

#: ../gecosws_config_assistant/controller/AutoSetupController.py:161
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:199
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:588
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:738
msgid "Do you want to disable the SSL certificate verification?"
msgstr "¿Desea desactivar la validación de certificados SSL?"

#: ../gecosws_config_assistant/controller/AutoSetupController.py:164
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:202
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:591
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:741
msgid "Subject:"
msgstr "Objeto:"

#: ../gecosws_config_assistant/controller/AutoSetupController.py:167
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:204
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:594
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:743
msgid "Issuer:"
msgstr "Emisor:"

#: ../gecosws_config_assistant/controller/AutoSetupController.py:170
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:207
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:598
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:746
msgid "Serial Number:"
msgstr "Número de serie:"

#: ../gecosws_config_assistant/controller/AutoSetupController.py:172
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:209
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:600
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:748
msgid "Not before:"
msgstr "No antes:"

#: ../gecosws_config_assistant/controller/AutoSetupController.py:174
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:211
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:602
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:750
msgid "Not after:"
msgstr "No después:"

#: ../gecosws_config_assistant/controller/AutoSetupController.py:195
#: ../gecosws_config_assistant/controller/AutoSetupController.py:227
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:233
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:243
msgid "Can't connect to GECOS CC!"
msgstr "¡Imposible conectar al CC GECOS!"

#: ../gecosws_config_assistant/controller/AutoSetupController.py:196
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:234
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:637
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:779
msgid "SSL ERROR:"
msgstr "ERROR de SSL:"

#: ../gecosws_config_assistant/controller/AutoSetupController.py:205
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:147
msgid "The Username field is empty!"
msgstr "¡El campo Usuario está vacío!"

#: ../gecosws_config_assistant/controller/AutoSetupController.py:217
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:158
msgid "The Password field is empty!"
msgstr "¡El campo Contraseña está vacío!"

#: ../gecosws_config_assistant/controller/AutoSetupController.py:228
msgid "Please double-check all the data and your network setup."
msgstr "Por favor revise todos los datos y su configuración de red."

#: ../gecosws_config_assistant/controller/AutoSetupController.py:249
msgid "Please wait"
msgstr "Por favor espere"

#: ../gecosws_config_assistant/controller/AutoSetupController.py:259
msgid "Error getting data"
msgstr "Error obteniendo datos"

#: ../gecosws_config_assistant/controller/AutoSetupController.py:261
msgid "Can't read auto setup configuration data from GECOS Control Center!"
msgstr ""
"¡No se pueden leer los datos de autoconfiguración desde el Centro de Control "
"GECOS!"

#: ../gecosws_config_assistant/controller/AutoSetupController.py:267
msgid "Success getting data from GECOS server"
msgstr "Exito al obtener los datos desde el servidor GECOS"

#: ../gecosws_config_assistant/controller/LocalUserController.py:84
msgid "The login field is empty!"
msgstr "¡El campo Login está vacío!"

#: ../gecosws_config_assistant/controller/LocalUserController.py:93
msgid "The login field contains not allowed characters!"
msgstr "¡El campo Login contiene caracteres no permitidos!"

#: ../gecosws_config_assistant/controller/LocalUserController.py:101
msgid "The name field is empty!"
msgstr "¡El campo Nombre está vacío!"

#: ../gecosws_config_assistant/controller/LocalUserController.py:111
msgid "The password field is empty!"
msgstr "¡El campo Contraseña está vacío!"

#: ../gecosws_config_assistant/controller/LocalUserController.py:119
msgid "The password field contains not allowed characters."
msgstr "El campo Contraseña contiene caracteres no permitidos"

#: ../gecosws_config_assistant/controller/LocalUserController.py:168
msgid "Do you really want to delete this user? "
msgstr "¿Realmente desea borrar este usuario?"

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:339
msgid ""
"The user authentication data has changed.\n"
"Do you want to setup the user authentication method using this new data?"
msgstr ""
"Los datos de autenticación del usuario han cambiado.\n"
"¿Desea configurar el método de autenticación de usuarios usando estos nuevos "
"datos?"

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:387
msgid "Authentication method saved!"
msgstr "Método de Autenticación configurado!"

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:391
msgid "Authentication method failed!"
msgstr "Método de Autenticación falló!"

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:418
msgid "The URI field is empty!"
msgstr "¡El campo URI está vacío!"

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:427
msgid "Malformed LDAP URI!"
msgstr "¡URI de LDAP mal formada!"

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:428
msgid "Please check that the URI starts with 'ldap(s)://'."
msgstr "Por favor, compruebe que la URI empieza con 'ldap://' o 'ldaps://'."

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:437
msgid "The users base DN field is empty!"
msgstr "¡El campo base DN de usuarios está vacío!"

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:445
msgid "Can't connect to LDAP server!"
msgstr "¡No se puede conectar al servidor de LDAP!"

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:446
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:536
msgid "Please check all the fields and your network connection."
msgstr "Por favor compruebe todos los campos y su conexión con la red!"

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:463
msgid "Bad netbios hostname!"
msgstr "¡El hosname no cumple los requisitos de Netbios!"

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:464
msgid "Please change the hostname of this computer."
msgstr "Por favor cambie el hostname de este ordenador."

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:473
msgid "The Domain field is empty!"
msgstr "¡El campo Dominio está vacío!"

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:494
msgid "Can't resolv the Active Directory Domain name!"
msgstr "¡No se puede resolver el nombre de dominio de Active Directory!"

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:496
msgid "Please check the Domain field and your DNS configuration."
msgstr "Por favor compurebe el campo Dominio y su configuración de DNS."

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:506
msgid "The Workgroup field is empty!"
msgstr "El campo Grupo de trabajo está vacío!"

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:516
msgid "The AD administrator user field is empty!"
msgstr "¡El campo usuario Administrador AD está vacío!"

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:526
msgid "The AD administrator password field is empty!"
msgstr "¡El campo contraseña de administrador AD está vacío!"

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:535
msgid "Can't connect to Active Directory server!"
msgstr "¡No se puede conectar con el servidor de Active Directory!"

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:244
msgid "Please double-check all the data and yournetwork setup."
msgstr "Por favor revise todos los datos y su configuración de red."

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:259
msgid "The GECOS workstation name field is empty!"
msgstr "¡El campo Nombre de estación de trabajo está vacío!"

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:277
msgid "You must select an OU!"
msgstr "¡Debe seleccionar una OU!"

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:293
msgid "Can't obtain data from OU!"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:295
msgid "Please double check the selected OU."
msgstr "Por favor revise la UO seleccionada."

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:309
msgid "The GECOS workstation name already exist!"
msgstr "¡El nombre de estación de trabajo ya existe!"

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:311
msgid "Please choose a different name."
msgstr "Por favor elija un nombre diferente"

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:405
msgid "Link to Chef"
msgstr "Vincular a Chef "

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:406
msgid "Register in GECOS CC"
msgstr "Registrar en CC GECOS"

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:411
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:435
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:447
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:682
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:866
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:907
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:942
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:954
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:967
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:977
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:1024
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:1036
msgid "IN PROCESS"
msgstr "EN PROCESO"

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:432
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:444
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:679
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:863
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:904
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:909
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:951
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:964
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:974
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:1021
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:1033
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:1038
msgid "DONE"
msgstr "HECHO"

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:480
msgid "There was an error while getting the client certificate"
msgstr "Ha ocurrido un error al obtener el certificado de cliente"

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:493
msgid "There was an error while saving the client certificate"
msgstr "Ha ocurrido un error al guardar el certificado de cliente"

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:636
msgid "Can't connect to GEMs repository!"
msgstr "¡No se puede conectar al repositrio de GEMas!"

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:650
msgid "There was an error while adding the GEMs repository:\n"
msgstr "Ha ocurrido un error al añadir el repositorio de GEMas:\n"

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:671
msgid "There was an error while installing a required GEM: "
msgstr "Ha ocurrido un error al instalar una GEMa requerida: "

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:778
msgid "Can't connect to Chef Server!"
msgstr "¡No se puede conectar con el servidor de Chef!"

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:808
msgid "Can't create/modify /etc/chef/client.rb file"
msgstr "¡No se puede crear/modificar el fichero  /etc/chef/client.rb!"

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:831
msgid "Can't link to chef server!"
msgstr "¡No se ha podido vincular al servidor de Chef!"

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:855
msgid "Can't create/modify /etc/chef.control file"
msgstr "No se puede crear/modificar el fichero /etc/chef.control"

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:876
msgid "Can't register the computer in GECOS CC"
msgstr "No se ha podido registar el ordenador en el CC GECOS"

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:896
msgid "Can't save /etc/gcc.control file"
msgstr "No se puede guardar el fichero /etc/gcc.control"

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:931
msgid "Local disconnection done!"
msgstr "¿Desconexión local?"

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:936
msgid "Unlink from Chef"
msgstr "Desvincular de Chef "

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:937
msgid "Unregister from GECOS CC"
msgstr "Desregistrar del CC GECOS"

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:989
msgid "Can't unregister the computer from GECOS CC"
msgstr "No se puede desregistrar el ordenador del CC GECOS"

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:1000
msgid "Can't remove /etc/chef.control file"
msgstr "No se puede borar el fichero /etc/chef.control"

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:1008
msgid "Can't remove /etc/chef/client.pem file"
msgstr "No se puede borrar el fichero /etc/chef/client.pem"

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:1017
msgid "Can't delete Chef node"
msgstr "No se puede borrar el nodo de Chef"

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:1029
msgid "Can't remove /etc/gcc.control file"
msgstr "No se puede borrar el fichero /etc/gcc.control"

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:1062
msgid "Can't get OUs from GECOS Control Center"
msgstr "No se pueden obtener las OUs desde el Centro de Control GECOS"


